version: '3.9'

services:
  backend:
    container_name: openstudyindia_c
    image: openstudyindia
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - openstudyindia_network

  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5431:5432'  # Mapping port 5432 inside the container to 5431 on the host
    networks:
      - openstudyindia_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}

networks:
  openstudyindia_network:
